- name: Install Software
  hosts: all
  become: yes  # Ensure the tasks are run with administrative privileges
  gather_facts: yes
  tasks:
    - name: Ensure the directory exists
      win_file:
        path: C:\Temp\
        state: directory
        recurse: yes

    # - name: Install Chocolatey (if not already installed)
    #   win_chocolatey:
    #     name: chocolatey
    #     state: present

# Install Brave
    - name: Download Brave Browser Installer
      win_get_url:
        url: https://laptop-updates.brave.com/latest/winx64
        dest: C:\Temp\BraveBrowserSetup-x64.exe
    - name: Install Brave Browser
      win_package:
        path: C:\Temp\BraveBrowserSetup-x64.exe
        state: present
        arguments: /silent /install
    - name: Remove installer after installation
      win_file:
        path: C:\Temp\BraveBrowserSetup-x64.exe
        state: absent
    # - name: Ensure Brave is installed for all users
    #   win_regedit:
    #     path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Brave
    #     name: DisplayName
    #     data: Brave
    #     state: present

    - name: Install Bitwarden for Brave
      win_chocolatey:
        name: bitwarden-chrome
        state: present
        pinned: true



    - name: Remove installer after installation
      win_file:
        path: C:\Temp\*
        state: absent



  # - name: Install Chocolatry packages
  #   chocolatey.chocolatey.win_chocolatey:
  #     name:

        #- geforce-experience
        # - notepadplusplus
        # - mremoteng
        # - steam
        # - fpsmonitor
        # - icue
        # - lghub
        # - systeminformer-nightlybuilds
        # - samsung-magician
        # - discord
        # - thunderbird
        # - git
        # - vscode
        # - greenshot
  #    state: present

  # - name: Download GameFirst VI installer
  #   win_get_url:
  #     url: "https://aquacomputer.de/software.html?file=tl_files/aquacomputer/downloads/aquasuite/aquasuite_setup.exe"
  #     dest: "C:\\Users\\Public\\Downloads\\aquasuite_setup.exe"

  # - name: Install GameFirst VI
  #   win_shell: |
  #     Start-Process -FilePath "C:\\Users\\Public\\Downloads\\aquasuite_setup.exe" -ArgumentList "/quiet /norestart" -Wait
  #   args:
  #     executable: powershell

  # - name: Clean up installer
  #   win_file:
  #     path: "C:\\Users\\Public\\Downloads\\aquasuite_setup.exe"
  #     state: absent