- name: New PC Software Install
  hosts: all
  tasks:
    - name: Install PowerToys
      win_winget:
        name: Brave.Brave
    # - name: Update winget sources and accept agreements
    #   ansible.windows.win_shell: |
    #     winget source update --accept-package-agreements
    #   register: result
    #   become: true

    # - name: Install Brave
    #   ansible.windows.win_shell: |
    #     winget install -e --id Brave.Brave --accept-source-agreements
    

  # - name: Install Chocolatry packages
  #   chocolatey.chocolatey.win_chocolatey:
  #     name:
  #       - brave
        #- bitwarden-chrome
        #- geforce-experience
        # - notepadplusplus
        # - mremoteng
        # - steam
        # - fpsmonitor
        # - icue
        # - lghub
        # - systeminformer-nightlybuilds
        # - samsung-magician
        # - discord
        # - thunderbird
        # - git
        # - vscode
        # - greenshot
  #    state: present

  # - name: Download GameFirst VI installer
  #   win_get_url:
  #     url: "https://aquacomputer.de/software.html?file=tl_files/aquacomputer/downloads/aquasuite/aquasuite_setup.exe"
  #     dest: "C:\\Users\\Public\\Downloads\\aquasuite_setup.exe"

  # - name: Install GameFirst VI
  #   win_shell: |
  #     Start-Process -FilePath "C:\\Users\\Public\\Downloads\\aquasuite_setup.exe" -ArgumentList "/quiet /norestart" -Wait
  #   args:
  #     executable: powershell

  # - name: Clean up installer
  #   win_file:
  #     path: "C:\\Users\\Public\\Downloads\\aquasuite_setup.exe"
  #     state: absent