- name: Remove Windows 11 bloatware 
  hosts: all
  tasks:
    - name: Uninstall bloatware apps
      ansible.windows.win_shell: |
        Get-AppxPackage -Name {{ item }} | Remove-AppxPackage
      loop:
        - Microsoft.MicrosoftSolitaireCollection
        - Microsoft.ZuneMusic
        - Microsoft.Copilot
        - Microsoft.WindowsFeedbackHub
        - Microsoft.MicrosoftStickyNotes
        - Microsoft.GetHelp
        - Microsoft.GamingApp
        - Microsoft.BingSearch
        - Microsoft.BingNews
        - Microsoft.OutlookForWindows
        - Microsoft.ScreenSketch
        - Microsoft.MicrosoftOfficeHub
        - Microsoft.Todos
        - Microsoft.WindowsNotepad
        - Microsoft.Paint
        - Microsoft.PowerAutomateDesktop
        - MicrosoftCorporationII.QuickAssist
        - Microsoft.WindowsSoundRecorder
        - Microsoft.BingWeather
        - Microsoft.WindowsAlarms
    - name: Uninstall OneDrive
      ansible.windows.win_shell: |
        winget uninstall "Microsoft OneDrive"
    - name: Uninstall OClipchamp
      ansible.windows.win_shell: |
        winget uninstall "Microsoft Clipchamp"
    - name: Uninstall Microsoft Teams
      ansible.windows.win_shell: |
        winget uninstall "Microsoft Teams"
    - name: Uninstall Xbox 
      ansible.windows.win_shell: |
        winget uninstall "Xbox"
