- name: Install Software
  hosts: all
  become: yes  # Ensure the tasks are run with administrative privileges
  gather_facts: yes
  tasks:
    - name: Set region for msstore
      win_environment:
        name: "Region"
        value: "GB"
        level: "machine" # can be set to machine, process, user
    - name: Install Brave Browser using winget
      ansible.windows.win_shell: |
        winget install -e --id Brave.Brave --source winget --scope machine --accept-source-agreements --accept-package-agreements





 #      # - brave
        #- bitwarden-chrome
        #- geforce-experience
        # - notepadplusplus
        # - mremoteng
        # - steam
        # - fpsmonitor
        # - icue
        # - lghub
        # - systeminformer-nightlybuilds
        # - samsung-magician
        # - discord
        # - thunderbird
        # - git
        # - vscode
        # - greenshot

    - name: Remove installer after installation
      win_file:
        path: C:\Temp\*
        state: absent


 