- name: Install Brave Browser on Windows for all users
  hosts: all
  gather_facts: yes
  tasks:
    - name: Ensure the directory exists
      win_file:
        path: C:\Temp\
        state: directory
        recurse: yes

    - name: Download Brave Browser Installer
      win_get_url:
        url: https://github.com/brave/brave-browser/releases/download/v1.57.55/BraveBrowserSetup-x64.exe
        dest: C:\Temp\BraveBrowserSetup-x64.exe

    - name: Install Brave Browser
      win_package:
        path: C:\Temp\BraveBrowserSetup-x64.exe
        state: present
        arguments: /silent /install

    - name: Remove installer after installation
      win_file:
        path: C:\Temp\BraveBrowserSetup-x64.exe
        state: absent

    - name: Ensure Brave is installed for all users
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Brave
        name: DisplayName
        data: Brave
        state: present