- name: New PC Software Install
  hosts: all
  tasks:
    - name: Set region for msstore
      win_environment:
        name: "Region"
        value: "GB"
        level: "machine" # can be set to machine, process, user

    # - name: Install Brave Browser using winget
    #   ansible.windows.win_shell: |
    #     $env:Region = "US"  # Set region
    #     winget install -e --id Brave.Brave --source winget --scope machine --accept-source-agreements --accept-package-agreements
    #   become: true
    #   args:
    #     executable: powershell
    - name: Install application via winget (with elevated privileges)
      win_shell: |
        Start-Process winget -ArgumentList "install Brave" -Verb RunAs
      args:
        executable: powershell.exe


      
# winget install brave --source msstore --scope machine --accept-source-agreements --accept-package-agreements
#      become: true


#      become: true
    # - name: Update winget sources and accept agreements
    #   ansible.windows.win_shell: |
    #     winget source update --accept-package-agreements --accept-source-agreements
    #   register: result
    #   become: true

  # - name: Install Chocolatry packages
  #   chocolatey.chocolatey.win_chocolatey:
  #     name:
  #       - brave
        #- bitwarden-chrome
        #- geforce-experience
        # - notepadplusplus
        # - mremoteng
        # - steam
        # - fpsmonitor
        # - icue
        # - lghub
        # - systeminformer-nightlybuilds
        # - samsung-magician
        # - discord
        # - thunderbird
        # - git
        # - vscode
        # - greenshot
  #    state: present

  # - name: Download GameFirst VI installer
  #   win_get_url:
  #     url: "https://aquacomputer.de/software.html?file=tl_files/aquacomputer/downloads/aquasuite/aquasuite_setup.exe"
  #     dest: "C:\\Users\\Public\\Downloads\\aquasuite_setup.exe"

  # - name: Install GameFirst VI
  #   win_shell: |
  #     Start-Process -FilePath "C:\\Users\\Public\\Downloads\\aquasuite_setup.exe" -ArgumentList "/quiet /norestart" -Wait
  #   args:
  #     executable: powershell

  # - name: Clean up installer
  #   win_file:
  #     path: "C:\\Users\\Public\\Downloads\\aquasuite_setup.exe"
  #     state: absent