- name: Remove Windows 11 bloatware 
  hosts: all
  tasks:
    - name: Uninstall bloatware apps
  win_shell: |
    Get-AppxPackage -Name {{ item }} | Remove-AppxPackage
  loop:
    - Microsoft.MicrosoftSolitaireCollection
