# - name: New PC Software Install
#   hosts: all
#   tasks:
#     - name: Set region for msstore
#       win_environment:
#         name: "Region"
#         value: "GB"
#         level: "machine" # can be set to machine, process, user
#     - name: Install Brave Browser using winget
#       ansible.windows.win_shell: |
#         winget install -e --id Brave.Brave --source winget --scope machine --accept-source-agreements --accept-package-agreements
      

- name: Install Brave Browser using Chocolatey for All Users
  hosts: all
  become: yes  # Ensure the tasks are run with administrative privileges
  gather_facts: yes
  tasks:

    - name: Install Chocolatey (if not already installed)
      win_chocolatey:
        name: chocolatey
        state: present
        version: latest

    - name: Install Brave using Chocolatey
      win_chocolatey:
        name: brave
        state: present


  # - name: Install Chocolatry packages
  #   chocolatey.chocolatey.win_chocolatey:
  #     name:
  #       - brave
        #- bitwarden-chrome
        #- geforce-experience
        # - notepadplusplus
        # - mremoteng
        # - steam
        # - fpsmonitor
        # - icue
        # - lghub
        # - systeminformer-nightlybuilds
        # - samsung-magician
        # - discord
        # - thunderbird
        # - git
        # - vscode
        # - greenshot
  #    state: present

  # - name: Download GameFirst VI installer
  #   win_get_url:
  #     url: "https://aquacomputer.de/software.html?file=tl_files/aquacomputer/downloads/aquasuite/aquasuite_setup.exe"
  #     dest: "C:\\Users\\Public\\Downloads\\aquasuite_setup.exe"

  # - name: Install GameFirst VI
  #   win_shell: |
  #     Start-Process -FilePath "C:\\Users\\Public\\Downloads\\aquasuite_setup.exe" -ArgumentList "/quiet /norestart" -Wait
  #   args:
  #     executable: powershell

  # - name: Clean up installer
  #   win_file:
  #     path: "C:\\Users\\Public\\Downloads\\aquasuite_setup.exe"
  #     state: absent