- name: Install Software
  hosts: all
  tasks:
    - name: Ensure the directory exists
      win_file:
          path: C:\Temp\
          state: directory
          recurse: yes

    - name: Download Brave Browser
      ansible.windows.win_get_url:
        url: https://laptop-updates.brave.com/latest/winx64
        dest: C:\Temp\BraveBrowserSetup-x64.exe
        force: false
    - name: Install Brave Browser
      win_package:
        path: https://laptop-updates.brave.com/latest/winx64
        state: present
        arguments: /silent /install
    
    - name: Download the Notepad++ installer
      ansible.windows.win_get_url:
      url: https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.7.1/npp.8.7.1.Installer.x64.exe
      dest: C:\Temp\npp_installer.exe
    - name: Install Notepad++ using the installer
      ansible.windows.win_package:
        path: C:\Temp\npp_installer.exe
        state: present
        arguments: /S

    #  not working
    # - name: Download the NVIDIA GeForce Experience installer
    #   ansible.windows.win_get_url:
    #     url: https://uk.download.nvidia.com/GFE/GFEClient/3.28.0.417/GeForce_Experience_v3.28.0.417.exe
    #     dest: C:\Temp\GeForce_Experience_Installer.exe
    # - name: Install NVIDIA GeForce Experience using the installer
    #   ansible.windows.win_package:
    #     path: C:\Temp\GeForce_Experience_Installer.exe
    #     state: present
    #     arguments: /S
    

    - name: Download Steam
      ansible.windows.win_get_url:
        url: https://cdn.fastly.steamstatic.com/client/installer/SteamSetup.exe
        dest: C:\Temp\SteamSetup.exe
        force: false
    - name: Install Steam
      ansible.windows.win_package:
        path: C:\Temp\SteamSetup.exe
        state: present
        arguments: /S


    # - name: Download FPSMonitor
    #   ansible.windows.win_get_url:
    #     url: https://www.fpsmon.com/bin/fpsmon-5503.exe
    #     dest: C:\Temp\fpsmon-5503.exe
    #     force: false
    # - name: Install FPSMonitor
    #   ansible.windows.win_package:
    #     path: C:\Temp\fpsmon-5503.exe
    #     state: present
    #     arguments: /S



    # - name: Download iQUE
    #   ansible.windows.win_get_url:
    #     url: https://www3.corsair.com/software/CUE_V5/public/modules/windows/installer/Install%20iCUE.exe
    #     dest: C:\Temp\iQUE.exe
    #     force: false
    # - name: Download Logitech Ghub
    #   ansible.windows.win_get_url:
    #     url: https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub_installer.exe
    #     dest: C:\Temp\lghub_installer.exe
    #     force: false
    # - name: Download System Informer
    #   ansible.windows.win_get_url:
    #     url: https://downloads.sourceforge.net/project/systeminformer/systeminformer-3.1.24298-release-setup.exe?ts=gAAAAABnROHjEBxvfaTtqDx0t3pK0dkZtaYxQp1FzKtxecha-zQNXV2r10q3V8EjscJSsbFvu3zBrMXW23A79lo_DBiaekFBtQ%3D%3D&r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fsysteminformer%2Ffiles%2Fsysteminformer-3.1.24298-release-setup.exe%2Fdownload
    #     dest: C:\Temp\systeminformer.exe
    #     force: false
    # - name: Download aquasuite
    #   ansible.windows.win_get_url:
    #     url: https://aquacomputer.de/software.html?file=tl_files/aquacomputer/downloads/aquasuite/aquasuite_setup.exe
    #     dest: C:\Temp\aquasuite_setup.exe
    #     force: false


# Instalation 

    

  # - name: Install Bitwarden for Brave
  #   win_chocolatey:
  #     name: bitwarden-chrome
  #     state: present
  #     pinned: false



  # - name: Remove installer after installation
  #   win_file:
  #     path: C:\Temp\*
  #     state: absent

        # - samsung-magician
        # - discord
        # - thunderbird
        # - git
        # - vscode
        # - greenshot



 