- name: Install Software
  hosts: all
  tasks:
    - name: Set region for msstore
      win_environment:
        name: "Region"
        value: "GB"
        level: "machine" # can be set to machine, process, user

    - name: Install Brave Browser
      ansible.windows.win_shell: |
        winget install -e --id Brave.Brave --source winget --scope machine --accept-source-agreements --accept-package-agreements
      ignore_errors: true
    - name: Install GeForceExperience
      ansible.windows.win_shell: |
        winget install -e --id Nvidia.GeForceExperience --source winget --scope machine --accept-source-agreements --accept-package-agreements
      ignore_errors: true

 #      

        #- geforce-experience    winget install -e --id Nvidia.GeForceExperience
        # - notepadplusplus
        # - mremoteng
        # - steam
        # - fpsmonitor
        # - icue
        # - lghub
        # - systeminformer-nightlybuilds
        # - samsung-magician
        # - discord
        # - thunderbird
        # - git
        # - vscode
        # - greenshot



 