- hosts: all
  tasks:
  - name: Install 7-zip
    chocolatey.chocolatey.win_chocolatey:
      name:
        - 7zip
        - notepadplusplus
        - mremoteng
      state: present
      state: present
...
