- name: Check Disk Space Usage
  hosts: all
  tasks:
    - name: Get disk facts
      win_disk_facts:



    - name: system disk size
      debug:
        msg: '{{ disksize_gb_human }}'
      vars:
        # Get first system disk
        disk: '{{ ansible_facts.disks|selectattr("system_disk")|first }}'

        # Show disk size in Gigabytes
        disksize_gb_human: '{{ disk.size|filesizeformat }}'        # returns "240.1 GB" (human readable)
       