- name: Check Disk Space Usage
  hosts: all
  tasks:
    - name: Get disk facts
      ansible.windows.win_powershell:
        script: (Get-CimInstance -ClassName Win32_LogicalDisk | Select-Object -Property DeviceID,@{'Name' = 'FreeSpace (GB)'; Expression= { [int]($_.FreeSpace / 1GB) }} | Measure-Object -Property 'FreeSpace (GB)' -Sum).Sum
#        msg: "{{OUTPUT.}}"