---
- name: Search windows updates
  hosts: windows_systems
  gather_facts: yes

  tasks:

  - block:
    - name: Search updates
      win_updates:
        category_names:
        - CriticalUpdates
        - SecurityUpdates
        - UpdateRollups
        reboot: no
        state: searched
      become: yes
      become_method: runas
      become_user: SYSTEM
      register: update_results

    - name: Report results
      debug:
        msg: |
          {% for k in update_results.updates %}
          {{ update_results.updates[k].title }}
          {% endfor %}