---
- hosts: all
  gather_facts: no     
  tasks:
    - block:
        - name: Checking for Available Windows Updates
          win_updates:
            category_names: 
              - CriticalUpdates
              - DefinitionUpdates
              - SecurityUpdates
              - Updates
              - UpdateRollups
            state: searched
          register: available_updates
        - name: List missing Updates
          debug: 
            msg: "{{ inventory_hostname }} has {{ available_updates.found_update_count }} updates available. The following updates are available for install: {{ available_updates.contains.item }}"
            with_items: "{{ title }}"