---
- name: Search windows updates
  hosts: all
  gather_facts: yes

  tasks:

  - block:
    - name: Search updates
      win_updates:
        category_names:
        - CriticalUpdates
        - SecurityUpdates
        - UpdateRollups
        state: searched
      register: update_results
    - name: Report results
      debug:
        msg: |
          {% for k in update_results.updates %}
          {{ update_results.updates[k].title }}
          {% endfor %}