- hosts: all
  tasks:
  - name: win_regedit-test
    windows.win_regedit:
      path: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
      name: TaskbarSi
      data: 0
      type: dword
...
